export const adaptarMuestraDesdeApi = (apiMuestra) => ({
    id: apiMuestra.id,
    puntoGeneracion: apiMuestra.puntoGeneracion,
    frascos: apiMuestra.frascos,
    material: apiMuestra.material,
    medico: apiMuestra.medico,
    preparador: apiMuestra.preparador,
    localizacion: apiMuestra.localizacion,
    diagnostico: apiMuestra.diagnostico,
    observaciones: apiMuestra.observaciones,
    paciente: apiMuestra.paciente,
    tipo_muestra: apiMuestra.tipo_muestra,
    subtipo_muestra: apiMuestra.subtipo_muestra,
    fechaAlta: apiMuestra.created_at,
    atb: apiMuestra.atb,
});
  
export const adaptarMuestraParaApi = (appMuestra) => ({
    nombre: appMuestra.nombre,
    apellido: appMuestra.apellido,
    dni: appMuestra.dni,
    obra_social: appMuestra.obraSocialSelected,
    punto_generacion: appMuestra.puntoGeneracionSelected,
    tipo_muestra_id: appMuestra.tipoMuestraSelected,
    subtipo_muestra_id: appMuestra.subtipoMuestraSelected,
    frascos: appMuestra.frascos,
    material: appMuestra.material,
    medico: appMuestra.medicoSolicitante,
    preparador: appMuestra.preparador,
    localizacion: appMuestra.localizacion,
    diagnostico: appMuestra.diagnostico,
    observaciones: appMuestra.observaciones,
    atb: appMuestra.atb,
});